project-key: AUT

name: Autoencoder on CIFAR10
description: From blog post.
tags: [cifar10-ae]

parameters:
  encoding_dim:
    value: 256
    description: "Length on encoding vector."
  epochs: 50
  batch_size: 256
  optimizer: "adam"
